-- ============================================
-- VERTEX AGENT DATABASE SCHEMA
-- ============================================

-- Function to update updated_at timestamp (CREATE THIS FIRST!)
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ language 'plpgsql';

-- Conversations
CREATE TABLE IF NOT EXISTS conversations (
    id SERIAL PRIMARY KEY,
    session_id UUID UNIQUE NOT NULL,
    user_id VARCHAR(100), -- Optional user identification
    title VARCHAR(255), -- Auto-generated conversation title
    started_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_activity TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    is_active BOOLEAN DEFAULT true
);

-- Messages
CREATE TABLE IF NOT EXISTS messages (
    id SERIAL PRIMARY KEY,
    conversation_id INTEGER NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
    role VARCHAR(20) NOT NULL CHECK (role IN ('user', 'assistant', 'system')),
    content TEXT NOT NULL,
    tool_calls JSONB, -- Store tool calls made by assistant
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Alerts
CREATE TABLE IF NOT EXISTS alerts (
    id SERIAL PRIMARY KEY,
    alert_type VARCHAR(50) NOT NULL, -- 'low_stock', 'stockout_risk', 'reorder_needed', 'critical_part'
    severity VARCHAR(20) NOT NULL CHECK (severity IN ('low', 'medium', 'high', 'critical')),
    part_number VARCHAR(100) NOT NULL,
    part_description TEXT,
    current_stock DECIMAL(10,2),
    reorder_point DECIMAL(10,2),
    stock_percentage DECIMAL(5,2), -- Percentage of stock vs reorder point
    estimated_days_to_stockout INTEGER, -- Based on consumption trends
    message TEXT NOT NULL,
    recommendation TEXT, -- AI-generated recommendation
    auto_generated BOOLEAN DEFAULT true,
    acknowledged BOOLEAN DEFAULT false,
    acknowledged_by VARCHAR(100),
    acknowledged_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMP -- Auto-dismiss old alerts
);

-- Learned Patterns (AI insights)
CREATE TABLE IF NOT EXISTS learned_patterns (
    id SERIAL PRIMARY KEY,
    pattern_type VARCHAR(50) NOT NULL, -- 'seasonal_demand', 'consumption_trend', 'lead_time_variance'
    part_number VARCHAR(100),
    pattern_data JSONB NOT NULL, -- Flexible storage for pattern metadata
    confidence_score DECIMAL(5,2) CHECK (confidence_score >= 0 AND confidence_score <= 100),
    insights TEXT, -- Human-readable insights
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    valid_until TIMESTAMP -- Pattern expiry date
);

-- Autonomous Actions Log
CREATE TABLE IF NOT EXISTS autonomous_actions (
    id SERIAL PRIMARY KEY,
    action_type VARCHAR(50) NOT NULL, -- 'alert_created', 'pattern_detected', 'reorder_suggested'
    part_number VARCHAR(100),
    action_data JSONB NOT NULL, -- Details of the action taken
    success BOOLEAN DEFAULT true,
    error_message TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_conversations_session_id ON conversations(session_id);
CREATE INDEX IF NOT EXISTS idx_conversations_last_activity ON conversations(last_activity);

CREATE INDEX IF NOT EXISTS idx_messages_conversation_id ON messages(conversation_id);
CREATE INDEX IF NOT EXISTS idx_messages_created_at ON messages(created_at);

CREATE INDEX IF NOT EXISTS idx_alerts_acknowledged ON alerts(acknowledged);
CREATE INDEX IF NOT EXISTS idx_alerts_severity ON alerts(severity);
CREATE INDEX IF NOT EXISTS idx_alerts_created_at ON alerts(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_alerts_part_number ON alerts(part_number);

CREATE INDEX IF NOT EXISTS idx_learned_patterns_part_number ON learned_patterns(part_number);
CREATE INDEX IF NOT EXISTS idx_learned_patterns_type ON learned_patterns(pattern_type);

CREATE INDEX IF NOT EXISTS idx_autonomous_actions_created_at ON autonomous_actions(created_at DESC);

-- Trigger to auto-update updated_at (NOW the function exists!)
CREATE TRIGGER update_learned_patterns_updated_at BEFORE UPDATE ON learned_patterns
FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- View for active alerts
CREATE OR REPLACE VIEW active_alerts AS
SELECT 
    a.*,
    CASE 
        WHEN a.severity = 'critical' THEN 1
        WHEN a.severity = 'high' THEN 2
        WHEN a.severity = 'medium' THEN 3
        ELSE 4
    END as severity_order
FROM alerts a
WHERE a.acknowledged = false 
  AND (a.expires_at IS NULL OR a.expires_at > CURRENT_TIMESTAMP)
ORDER BY severity_order ASC, a.created_at DESC;

COMMENT ON TABLE conversations IS 'Chat conversation sessions';
COMMENT ON TABLE messages IS 'Individual messages within conversations';
COMMENT ON TABLE alerts IS 'Autonomous alerts generated by the system';
COMMENT ON TABLE learned_patterns IS 'AI-learned patterns and insights';
COMMENT ON TABLE autonomous_actions IS 'Log of all autonomous actions taken by the system';